title: Abubakar Riaz
description: Principal DevOps Engineer | Azure-Certified | Full Stack .NET Developer | SQL Server Trainer

url: "https://abubakarriaz.com.pk"
baseurl: ""

author:
  name: Abubakar Riaz

show_downloads: false

exclude:
  - README.md
  - CLAUDE.md
  - Gemfile
  - Gemfile.lock
  - .claude/
